### ISSUE TITLE
standard port instead of 3000

### ISSUE THREAD

**Issue by gufmar** [input-output-hk/iohk-ops#223]
(same suggestion posted in deadalus repository)

It looks like a noticeable number of users has problems using Daedalus just because their computer (AV Suite) or local network (LAN/WAN) does not allow connections to the 7 bootstrap servers listening on port 3000 
I would suggest introducing a fallback on port 443 (HTTPS) or a complete switch to such a standard port.

**Comment by domenkozar** [comment]
What is a "standard port"?

**Comment by gufmar** [comment]
Generally, I would say one of the well-known ports  as listed on https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers#Well-known_ports
Whatever integer value, it should become one having the highest probability of not being blocked by local, gateway or ISP based firewall rules for outgoing connections. Port 443 for https connections should be a very good choice. 
In order to seamlessly support both existing clients on port 3000 and new clients on the "well-known" port it would be best to let the server listen on both ports. (or let a firewall rule or local proxy translate it to the other port) until no user is using the current releases anymore.

Running on such stand ports will also help to prevent the cardano-network from being blocked by some providers. 

Clearly, this is not an easy step but better think about it now in the bootstrap era...

**Comment by rvl** [comment]
Thanks @gufmar Yes it would definitely make sense for the port to be configurable by the user if the node needs to be accessed on the Internet. This part is handled by cardano-sl and will definitely be changing in the upcoming [Shelley release](https://cardanoroadmap.com/#shelley-decentralised).
