### ISSUE TITLE
Build of iohk-ops fails

### ISSUE THREAD

**Issue by DanielRrr** [input-output-hk/iohk-ops#277]
Build of `iohk-ops` fails with the the next message:
`error: build of ‘/nix/store/jf1jwbkii4b3cyd19k701wr6rbivdsan-cardano-sl-36f9fcc.drv’ failed`

If I checkout to `slow-fallocate` branch and move to `slow-fallocate` directory, then build fails too with similar message:
`error: build of ‘/nix/store/jf1jwbkii4b3cyd19k701wr6rbivdsan-cardano-sl-36f9fcc.drv’ failed`

**Comment by DanielRrr** [comment]
I think, I understood the reason

**Comment by rvl** [comment]
Please share

**Comment by DanielRrr** [comment]
@rvl, that's quite ridiculous mistake of mine. I forgot to make `$(nix-build release.nix -A connect.mainnetWallet)` on cardano.

**Comment by DanielRrr** [comment]
And something like that on `iohk-ops`:
```iohk-ops rogozindaniil$ nix-build
trace: fetching nixpkgs
building '/nix/store/f7fn52clbl6mxh1pncbpvq7b9il7dlbw-cardano-sl-36f9fcc.drv'...
dyld: Library not loaded: /usr/lib/system/libsystem_coretls.dylib
  Referenced from: /nix/store/v7i520r9c2p8z6vk26n53hfrxgqn8cl9-Libsystem-osx-10.11.6/lib/libSystem.B.dylib
  Reason: image not found
builder for '/nix/store/f7fn52clbl6mxh1pncbpvq7b9il7dlbw-cardano-sl-36f9fcc.drv' failed due to signal 6 (Abort trap: 6)
error: build of '/nix/store/f7fn52clbl6mxh1pncbpvq7b9il7dlbw-cardano-sl-36f9fcc.drv' failed```

**Comment by DanielRrr** [comment]
Is it problem with my nix or with `iohk-ops`?

**Comment by domenkozar** [comment]
It is hard to understand what you're doing. Can you provide a http://sscce.org/ - what commit/branch you used, what command you run, etc.

**Comment by domenkozar** [comment]
Ah - `slow-fallocate` will only work on Linux.
