### ISSUE TITLE
Hydra builders are too old for recent nixpkgs

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/iohk-ops#615]
I believe that we're on track to fix this via the new virtualized mac builders, but this is a tracking issue for how things are progressing.

See also:
- https://github.com/input-output-hk/tools/pull/4
- https://github.com/input-output-hk/plutus/issues/1076

**Comment by michaelpj** [comment]
Any update on this?

**Comment by michaelpj** [comment]
Any updates? @cleverca22, perhaps?

**Comment by disassembler** [comment]
sarov is now mojave. New mac minis arrived today. I'm closing this out.
